apiVersion: apps/v1 #
kind: Deployment
metadata:
  name: node-server
spec:
  selector:
    matchLabels:
      app: node-server
  replicas: 4
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
        - name: node-server
          image: exampledriven/node-server:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: node-server
  labels:
    app: node-server
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: node-server

---

apiVersion: apps/v1 #
kind: Deployment
metadata:
  name: node-client
spec:
  selector:
    matchLabels:
      app: node-client
  replicas: 4
  template:
    metadata:
      labels:
        app: node-client
    spec:
      containers:
        - name: node-client
          image: exampledriven/node-client:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: node-client
  labels:
    app: node-client
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: node-client
  type: NodePort